### PR TITLE
extract etag cache into its own service

### LINKED ISSUE #37: Configuration caching issue
I started with a new Graylog installation, empty database and thus without any collector configuration.

Apart from #36, I am also seeing that the filebeat and nxlog configurations are not updated once I created a configuration in the server. Only after restarting the sidecar process the new configurations get fetched.

I guess there is an issue with the new configuration caching system. To reproduce it, it should be enough to  start a sidecar with a tag for which no configuration exists.

This is a multi node setup of Graylog 2.2.0-alpha.5-SNAPSHOT+1720c48 with sidecar 5e577167b55db1bdd4d99c05cacfe0d2fe13593a.

### PR DESCRIPTION
**Pull request by kroepke**
* propagate etag invalidations across all servers in the cluster (as cluster events)
* always invalidates all etags, even though we could probably be smarter about which ones to reload

fixes #37

### CODE REVIEW

File: src/main/java/org/graylog/plugins/collector/CollectorModule.java [hunk 1]
```diff
@@ -43,5 +45,7 @@ protected void configure() {
         addPermissions(CollectorRestPermissions.class);
 
         addAuditEventTypes(CollectorAuditEventTypes.class);
+
+        serviceBinder().addBinding().to(ConfigurationEtagService.class).in(Scopes.SINGLETON);
```
Comment (mariussturm) [inline src/main/java/org/graylog/plugins/collector/CollectorModule.java]: We see that on each request a new and empty cache instance is generated. Any idea why? Even when bind as singleton?

File: src/main/java/org/graylog/plugins/collector/configurations/rest/ConfigurationEtagService.java [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+    private ClusterEventBus clusterEventBus;
+
+    @Inject
+    public ConfigurationEtagService(MetricRegistry metricRegistry, EventBus eventBus, ClusterEventBus clusterEventBus) {
+        this.metricRegistry = metricRegistry;
+        this.eventBus = eventBus;
+        this.clusterEventBus = clusterEventBus;
+        cache = CacheBuilder.newBuilder()
+                .recordStats()
+                .expireAfterWrite(1, TimeUnit.HOURS)  // TODO magic number
```
Comment (mariussturm) [inline src/main/java/org/graylog/plugins/collector/configurations/rest/ConfigurationEtagService.java]: Should this be configurable and maybe a limited amount of cache entries?
